name: flutterappdemo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sliding_up_panel: ^1.0.2
  lint: ^1.0.0
  http: ^0.12.1
  provider: ^3.0.0
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/person.jpg
    - assets/images/room.png
    - assets/images/stone.jpg
    - assets/images/tree.jpg
    - assets/icons/play.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
